runtime: php55
api_version: 1
#application: cumeqetrekking
#version: 1 


handlers:

- url: /rest/.*
  script: src/main/php/api.php
  login: admin

- url: /rest/.*/.*
  script: src/main/php/api.php
  login: admin

- url: /notification
  script: src/main/php/notificator.php
  login: admin

- url: /test
  script: src/main/php/nottest.php

- url: /relatorio/Etapa/.*
  script:  src/main/php/etapaReport.php
  login: admin

- url: /SetPago.do
  script:  src/main/php/marcarPaga.php
  login: admin

- url: /AlteraGrid.do
  script:  src/main/php/alteraGrid.php
  login: admin

- url: /GerenciaResultado.do
  script:  src/main/php/performance.php
  login: admin

- url: /Inscrever.do
  script:  src/main/php/inscrever.php

- url: /app/rest/.*
  script: src/main/php/apiPub.php

- url: /app/rest/.*/.*
  script: src/main/php/apiPub.php

- url: /app/enhanced/.*
  script: src/main/php/app.php

- url: /web/grid.*
  script: src/main/php/old_grid.php

- url: /web/pgrid.*
  script: src/main/php/old_pregrid.php



- url: /admin/(.*\.(css|js|html))$  
  static_files:  src/main/webapp/admin/\1
  upload: src/main/webapp/admin/.*\.(css|js|html)$
  login: admin
  

- url: /
  script: src/main/php/redirect.php


- url: /open/(.*\.(css|js|html))$  
  static_files:  src/main/webapp/open/\1
  upload: src/main/webapp/open/.*\.(css|js|html)$

- url: /common/(.*\.(css|js|html))$  
  static_files:  src/main/webapp/common/\1
  upload: src/main/webapp/common/.*\.(css|js|html)$

- url: /bower_components/(.*\.(css|js|woff|ttf|woff2))$
  static_files: src/main/webapp/bower_components/\1
  upload: src/main/webapp/bower_components/.*\.(css|js|woff|ttf|woff2)$

- url: /endpoints/Login
  script: src/main/php/login.php

- url: /endpoints/senha/.*
  script: src/main/php/senha.php

- url: /endpoints/RegisterInscription
  script: src/main/php/userRegisterInscription.php

- url: /endpoints/User
  script: src/main/php/userManagement.php

- url: /endpoints/Register
  script: src/main/php/userRegister.php

- url: /task/GCMPush
  script: src/main/php/notificationTaskGCM.php
  login: admin

- url: /task/APNPush
  script: src/main/php/notificationTaskAPN.php
  login: admin

- url: /task/mailer
  script:  src/main/php/mailSender.php
  login: admin
